
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 02 13:01:38 CST 2023
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ADB_Duda = 28;
  public static final int Ad_Num_Cardinal = 6;
  public static final int CS_Condicionales = 35;
  public static final int CS_Finales = 40;
  public static final int Sustantivo = 2;
  public static final int Ad_Indefinido = 8;
  public static final int VER_AM = 17;
  public static final int Ad_Num_Ordinal = 7;
  public static final int VB_Regular = 20;
  public static final int ADB_Cantidad = 24;
  public static final int Ar_Definido = 9;
  public static final int Ad_Posesivo = 3;
  public static final int ADB_Modo = 25;
  public static final int Contracciones = 42;
  public static final int Ad_Demostrativo = 4;
  public static final int Pron_Demostrativo = 18;
  public static final int CC_Copulativas = 30;
  public static final int Pron_Interrogativo = 19;
  public static final int ADB_Afirmacion = 26;
  public static final int Preposicion = 29;
  public static final int CC_Distributivas = 32;
  public static final int CS_Concesivas = 38;
  public static final int PRON_I = 13;
  public static final int EOF = 0;
  public static final int Ad_Calificativo = 5;
  public static final int error = 1;
  public static final int PRON_PER_SING = 12;
  public static final int ADB_Tiempo = 22;
  public static final int PRON_PER_PLUR = 11;
  public static final int VER_SING = 15;
  public static final int CC_Explicativas = 34;
  public static final int VER_PLUR = 16;
  public static final int ADB_Lugar = 23;
  public static final int Ar_Indefinido = 10;
  public static final int VB_Irregulares = 21;
  public static final int CC_Adversativas = 31;
  public static final int CS_Comparativas = 39;
  public static final int Interjeccion = 41;
  public static final int PRO_PERSON = 14;
  public static final int CC_Disyuntivas = 33;
  public static final int CS_Consecutivas = 37;
  public static final int CS_Casuales = 36;
  public static final int ADB_Negacion = 27;
}

